### ISSUE TITLE
Como fazer deploy para desenvolvimento? (Baixar o projeto e instalar todas dependências)

### ISSUE THREAD

**Issue by goliveira-dev** [luantoningalvan/escolaltg#3]
Olá, estou começando a estudar desenvolvimento web e acho que seria uma boa um tutorial no README de como fazer deploy (vários projetos tem isso). Pois eu não entendi muito bem qual é a stack do projeto.

**Comment by luantoningalvan** [comment]
Obrigado pela sugestão! Acabei de fazer isso, também fiz um tutorial em vídeo também, espero que tenha sanado suas dúvidas.
